packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

allowBuilds:
  sharp: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@nestjs/common@11.1.29'
  - '@nestjs/core@11.1.29'
  - '@nestjs/platform-express@11.1.29'
  - '@nestjs/testing@11.1.29'
